export const SET_TRANSFER_FILTER = 'SET_TRANSFER_FILTER';
export const SET_SORTING = 'SET_SORTING';
export const TICKETS_REQUEST = 'TICKETS_REQUEST';
export const TICKETS_RECIEVED = 'TICKETS_RECIEVED';
export const URL_RECIEVED = 'URL_RECIEVED';
export const ERROR_RECIEVED = 'ERROR_RECIEVED';
export const TICKETS_FILTRATED = 'TICKETS_FILTRATED';
export const MORE_TICKETS = 'MORE_TICKETS';
